version: '3.3'

services:

    web:
        image: spurin/hexo
        restart: 'no'
        ports:
            - '8080:4000'
        volumes:
            - '.:/app'
        command: ['hexo', 'server']

